[package]
name = "hima-dango-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
hima-dango = { path = "../" }
wasm-bindgen = "0.2.95"
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]

